package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_LoginReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/


/////////////
public class epp_LoginReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public org.openrtk.idl.epp02.epp_Service m_services[] = null;

  public epp_LoginReq ()
  {
  } // ctor

  public epp_LoginReq (org.openrtk.idl.epp02.epp_Command _m_cmd, org.openrtk.idl.epp02.epp_Service[] _m_services)
  {
    m_cmd = _m_cmd;
    m_services = _m_services;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setServices(org.openrtk.idl.epp02.epp_Service[] value) { m_services = value; }
  public org.openrtk.idl.epp02.epp_Service[] getServices() { return m_services; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_services ["+(m_services != null ? java.util.Arrays.asList(m_services) : null)+"] }"; }

} // class epp_LoginReq
