package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_PollResDataUnion.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_PollResDataUnion implements org.omg.CORBA.portable.IDLEntity
{
  private org.openrtk.idl.epp02.epp_PollDomainTransfer ___m_domain_transfer;
  private org.openrtk.idl.epp02.epp_PollContactTransfer ___m_contact_transfer;
  private org.openrtk.idl.epp02.epp_PollResDataType __discriminator;
  private boolean __uninitialized = true;

  public epp_PollResDataUnion ()
  {
  }

  public org.openrtk.idl.epp02.epp_PollResDataType discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public org.openrtk.idl.epp02.epp_PollDomainTransfer m_domain_transfer ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifym_domain_transfer (__discriminator);
    return ___m_domain_transfer;
  }

  public void m_domain_transfer (org.openrtk.idl.epp02.epp_PollDomainTransfer value)
  {
    __discriminator = org.openrtk.idl.epp02.epp_PollResDataType.DOMAIN_TRANSFER;
    ___m_domain_transfer = value;
    __uninitialized = false;
  }

  private void verifym_domain_transfer (org.openrtk.idl.epp02.epp_PollResDataType discriminator)
  {
    if (discriminator != org.openrtk.idl.epp02.epp_PollResDataType.DOMAIN_TRANSFER)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public org.openrtk.idl.epp02.epp_PollContactTransfer m_contact_transfer ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifym_contact_transfer (__discriminator);
    return ___m_contact_transfer;
  }

  public void m_contact_transfer (org.openrtk.idl.epp02.epp_PollContactTransfer value)
  {
    __discriminator = org.openrtk.idl.epp02.epp_PollResDataType.CONTACT_TRANSFER;
    ___m_contact_transfer = value;
    __uninitialized = false;
  }

  private void verifym_contact_transfer (org.openrtk.idl.epp02.epp_PollResDataType discriminator)
  {
    if (discriminator != org.openrtk.idl.epp02.epp_PollResDataType.CONTACT_TRANSFER)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class epp_PollResDataUnion
