package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_LogoutOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public interface epp_LogoutOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.epp_LogoutReq data);
  org.openrtk.idl.epp02.epp_LogoutRsp getResponseData ();
} // interface epp_LogoutOperations
