package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Hello.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public interface epp_Hello extends epp_HelloOperations, org.openrtk.idl.epp02.epp_Action, org.omg.CORBA.portable.IDLEntity 
{
} // interface epp_Hello
