package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Command.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_Command implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Credentials m_creds = null;
  public org.openrtk.idl.epp02.epp_Unspec m_unspec = null;
  public String m_client_trid = null;

  public epp_Command ()
  {
  } // ctor

  public epp_Command (org.openrtk.idl.epp02.epp_Credentials _m_creds, org.openrtk.idl.epp02.epp_Unspec _m_unspec, String _m_client_trid)
  {
    m_creds = _m_creds;
    m_unspec = _m_unspec;
    m_client_trid = _m_client_trid;
  } // ctor

  public void setCreds(org.openrtk.idl.epp02.epp_Credentials value) { m_creds = value; }
  public org.openrtk.idl.epp02.epp_Credentials getCreds() { return m_creds; }

  public void setUnspec(org.openrtk.idl.epp02.epp_Unspec value) { m_unspec = value; }
  public org.openrtk.idl.epp02.epp_Unspec getUnspec() { return m_unspec; }

  public void setClientTrid(String value) { m_client_trid = value; }
  public String getClientTrid() { return m_client_trid; }

  public String toString() { return this.getClass().getName() + ": { m_creds ["+m_creds+"] m_unspec ["+m_unspec+"] m_client_trid ["+m_client_trid+"] }"; }

} // class epp_Command
