package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Unspec.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/


// message.
public interface epp_Unspec extends epp_UnspecOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface epp_Unspec
