package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Options.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_Options implements org.omg.CORBA.portable.IDLEntity
{
  public String m_version = null;
  public String m_lang = null;

  public epp_Options ()
  {
  } // ctor

  public epp_Options (String _m_version, String _m_lang)
  {
    m_version = _m_version;
    m_lang = _m_lang;
  } // ctor

  public void setVersion(String value) { m_version = value; }
  public String getVersion() { return m_version; }

  public void setLang(String value) { m_lang = value; }
  public String getLang() { return m_lang; }

  public String toString() { return this.getClass().getName() + ": { m_version ["+m_version+"] m_lang ["+m_lang+"] }"; }

} // class epp_Options
