package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostAddress.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:09 PM EDT
*/

public class epp_HostAddress implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.host.epp_HostAddressType m_type = null;
  public String m_ip = null;

  public epp_HostAddress ()
  {
  } // ctor

  public epp_HostAddress (org.openrtk.idl.epp02.host.epp_HostAddressType _m_type, String _m_ip)
  {
    m_type = _m_type;
    m_ip = _m_ip;
  } // ctor

  public void setType(org.openrtk.idl.epp02.host.epp_HostAddressType value) { m_type = value; }
  public org.openrtk.idl.epp02.host.epp_HostAddressType getType() { return m_type; }

  public void setIp(String value) { m_ip = value; }
  public String getIp() { return m_ip; }

  public String toString() { return this.getClass().getName() + ": { m_type ["+m_type+"] m_ip ["+m_ip+"] }"; }

} // class epp_HostAddress
