package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostInfo.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:09 PM EDT
*/

public interface epp_HostInfo extends epp_HostInfoOperations, org.openrtk.idl.epp02.epp_Action, org.omg.CORBA.portable.IDLEntity 
{
} // interface epp_HostInfo
