package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostInfoOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:10 PM EDT
*/

public interface epp_HostInfoOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.host.epp_HostInfoReq parms);
  org.openrtk.idl.epp02.host.epp_HostInfoRsp getResponseData ();
} // interface epp_HostInfoOperations
