package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostStatus.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:09 PM EDT
*/

public class epp_HostStatus implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.host.epp_HostStatusType m_type = null;
  public String m_lang = null;
  public String m_value = null;

  public epp_HostStatus ()
  {
  } // ctor

  public epp_HostStatus (org.openrtk.idl.epp02.host.epp_HostStatusType _m_type, String _m_lang, String _m_value)
  {
    m_type = _m_type;
    m_lang = _m_lang;
    m_value = _m_value;
  } // ctor

  public void setType(org.openrtk.idl.epp02.host.epp_HostStatusType value) { m_type = value; }
  public org.openrtk.idl.epp02.host.epp_HostStatusType getType() { return m_type; }

  public void setLang(String value) { m_lang = value; }
  public String getLang() { return m_lang; }

  public void setValue(String value) { m_value = value; }
  public String getValue() { return m_value; }

  public String toString() { return this.getClass().getName() + ": { m_type ["+m_type+"] m_lang ["+m_lang+"] m_value ["+m_value+"] }"; }

} // class epp_HostStatus
