package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostUpdateAddRemove.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:10 PM EDT
*/


///////////////////
public class epp_HostUpdateAddRemove implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.host.epp_HostAddress m_addresses[] = null;
  public org.openrtk.idl.epp02.host.epp_HostStatus m_status[] = null;

  public epp_HostUpdateAddRemove ()
  {
  } // ctor

  public epp_HostUpdateAddRemove (org.openrtk.idl.epp02.host.epp_HostAddress[] _m_addresses, org.openrtk.idl.epp02.host.epp_HostStatus[] _m_status)
  {
    m_addresses = _m_addresses;
    m_status = _m_status;
  } // ctor

  public void setAddresses(org.openrtk.idl.epp02.host.epp_HostAddress[] value) { m_addresses = value; }
  public org.openrtk.idl.epp02.host.epp_HostAddress[] getAddresses() { return m_addresses; }

  public void setStatus(org.openrtk.idl.epp02.host.epp_HostStatus[] value) { m_status = value; }
  public org.openrtk.idl.epp02.host.epp_HostStatus[] getStatus() { return m_status; }

  public String toString() { return this.getClass().getName() + ": { m_addresses ["+(m_addresses != null ? java.util.Arrays.asList(m_addresses) : null)+"] m_status ["+(m_status != null ? java.util.Arrays.asList(m_status) : null)+"] }"; }

} // class epp_HostUpdateAddRemove
