package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainUpdateReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/

public class epp_DomainUpdateReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public String m_name = null;
  public org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove m_add = null;
  public org.openrtk.idl.epp02.domain.epp_DomainUpdateChange m_change = null;
  public org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove m_remove = null;

  public epp_DomainUpdateReq ()
  {
  } // ctor

  public epp_DomainUpdateReq (org.openrtk.idl.epp02.epp_Command _m_cmd, String _m_name, org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove _m_add, org.openrtk.idl.epp02.domain.epp_DomainUpdateChange _m_change, org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove _m_remove)
  {
    m_cmd = _m_cmd;
    m_name = _m_name;
    m_add = _m_add;
    m_change = _m_change;
    m_remove = _m_remove;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setAdd(org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove value) { m_add = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove getAdd() { return m_add; }

  public void setChange(org.openrtk.idl.epp02.domain.epp_DomainUpdateChange value) { m_change = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainUpdateChange getChange() { return m_change; }

  public void setRemove(org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove value) { m_remove = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainUpdateAddRemove getRemove() { return m_remove; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_name ["+m_name+"] m_add ["+m_add+"] m_change ["+m_change+"] m_remove ["+m_remove+"] }"; }

} // class epp_DomainUpdateReq
