package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainUpdateAddRemove.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/


/////////////////////
public class epp_DomainUpdateAddRemove implements org.omg.CORBA.portable.IDLEntity
{
  public String m_name_servers[] = null;
  public org.openrtk.idl.epp02.domain.epp_DomainContact m_contacts[] = null;
  public org.openrtk.idl.epp02.domain.epp_DomainStatus m_status[] = null;

  public epp_DomainUpdateAddRemove ()
  {
  } // ctor

  public epp_DomainUpdateAddRemove (String[] _m_name_servers, org.openrtk.idl.epp02.domain.epp_DomainContact[] _m_contacts, org.openrtk.idl.epp02.domain.epp_DomainStatus[] _m_status)
  {
    m_name_servers = _m_name_servers;
    m_contacts = _m_contacts;
    m_status = _m_status;
  } // ctor

  public void setNameServers(String[] value) { m_name_servers = value; }
  public String[] getNameServers() { return m_name_servers; }

  public void setContacts(org.openrtk.idl.epp02.domain.epp_DomainContact[] value) { m_contacts = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainContact[] getContacts() { return m_contacts; }

  public void setStatus(org.openrtk.idl.epp02.domain.epp_DomainStatus[] value) { m_status = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainStatus[] getStatus() { return m_status; }

  public String toString() { return this.getClass().getName() + ": { m_name_servers ["+(m_name_servers != null ? java.util.Arrays.asList(m_name_servers) : null)+"] m_contacts ["+(m_contacts != null ? java.util.Arrays.asList(m_contacts) : null)+"] m_status ["+(m_status != null ? java.util.Arrays.asList(m_status) : null)+"] }"; }

} // class epp_DomainUpdateAddRemove
