package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainUpdateChange.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/

public class epp_DomainUpdateChange implements org.omg.CORBA.portable.IDLEntity
{
  public String m_registrant = null;
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;

  public epp_DomainUpdateChange ()
  {
  } // ctor

  public epp_DomainUpdateChange (String _m_registrant, org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info)
  {
    m_registrant = _m_registrant;
    m_auth_info = _m_auth_info;
  } // ctor

  public void setRegistrant(String value) { m_registrant = value; }
  public String getRegistrant() { return m_registrant; }

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public String toString() { return this.getClass().getName() + ": { m_registrant ["+m_registrant+"] m_auth_info ["+m_auth_info+"] }"; }

} // class epp_DomainUpdateChange
