package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainCreateRsp.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/

public class epp_DomainCreateRsp implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Response m_rsp = null;
  public String m_name = null;
  public String m_roid = null;
  public String m_expiration_date = null;

  public epp_DomainCreateRsp ()
  {
  } // ctor

  public epp_DomainCreateRsp (org.openrtk.idl.epp02.epp_Response _m_rsp, String _m_name, String _m_roid, String _m_expiration_date)
  {
    m_rsp = _m_rsp;
    m_name = _m_name;
    m_roid = _m_roid;
    m_expiration_date = _m_expiration_date;
  } // ctor

  public void setRsp(org.openrtk.idl.epp02.epp_Response value) { m_rsp = value; }
  public org.openrtk.idl.epp02.epp_Response getRsp() { return m_rsp; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public void setExpirationDate(String value) { m_expiration_date = value; }
  public String getExpirationDate() { return m_expiration_date; }

  public String toString() { return this.getClass().getName() + ": { m_rsp ["+m_rsp+"] m_name ["+m_name+"] m_roid ["+m_roid+"] m_expiration_date ["+m_expiration_date+"] }"; }

} // class epp_DomainCreateRsp
