package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainCheckReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/


////////////////////
public class epp_DomainCheckReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public String m_names[] = null;

  public epp_DomainCheckReq ()
  {
  } // ctor

  public epp_DomainCheckReq (org.openrtk.idl.epp02.epp_Command _m_cmd, String[] _m_names)
  {
    m_cmd = _m_cmd;
    m_names = _m_names;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setNames(String[] value) { m_names = value; }
  public String[] getNames() { return m_names; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_names ["+(m_names != null ? java.util.Arrays.asList(m_names) : null)+"] }"; }

} // class epp_DomainCheckReq
