package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainInfoRsp.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/

public class epp_DomainInfoRsp implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Response m_rsp = null;
  public String m_name = null;
  public String m_roid = null;
  public org.openrtk.idl.epp02.domain.epp_DomainStatus m_status[] = null;
  public String m_registrant = null;
  public org.openrtk.idl.epp02.domain.epp_DomainContact m_contacts[] = null;
  public String m_name_servers[] = null;
  public String m_hosts[] = null;
  public String m_client_id = null;
  public String m_created_by = null;
  public String m_created_date = null;
  public String m_updated_by = null;
  public String m_updated_date = null;
  public String m_expiration_date = null;
  public String m_transfer_date = null;
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;

  public epp_DomainInfoRsp ()
  {
  } // ctor

  public epp_DomainInfoRsp (org.openrtk.idl.epp02.epp_Response _m_rsp, String _m_name, String _m_roid, org.openrtk.idl.epp02.domain.epp_DomainStatus[] _m_status, String _m_registrant, org.openrtk.idl.epp02.domain.epp_DomainContact[] _m_contacts, String[] _m_name_servers, String[] _m_hosts, String _m_client_id, String _m_created_by, String _m_created_date, String _m_updated_by, String _m_updated_date, String _m_expiration_date, String _m_transfer_date, org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info)
  {
    m_rsp = _m_rsp;
    m_name = _m_name;
    m_roid = _m_roid;
    m_status = _m_status;
    m_registrant = _m_registrant;
    m_contacts = _m_contacts;
    m_name_servers = _m_name_servers;
    m_hosts = _m_hosts;
    m_client_id = _m_client_id;
    m_created_by = _m_created_by;
    m_created_date = _m_created_date;
    m_updated_by = _m_updated_by;
    m_updated_date = _m_updated_date;
    m_expiration_date = _m_expiration_date;
    m_transfer_date = _m_transfer_date;
    m_auth_info = _m_auth_info;
  } // ctor

  public void setRsp(org.openrtk.idl.epp02.epp_Response value) { m_rsp = value; }
  public org.openrtk.idl.epp02.epp_Response getRsp() { return m_rsp; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public void setStatus(org.openrtk.idl.epp02.domain.epp_DomainStatus[] value) { m_status = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainStatus[] getStatus() { return m_status; }

  public void setRegistrant(String value) { m_registrant = value; }
  public String getRegistrant() { return m_registrant; }

  public void setContacts(org.openrtk.idl.epp02.domain.epp_DomainContact[] value) { m_contacts = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainContact[] getContacts() { return m_contacts; }

  public void setNameServers(String[] value) { m_name_servers = value; }
  public String[] getNameServers() { return m_name_servers; }

  public void setHosts(String[] value) { m_hosts = value; }
  public String[] getHosts() { return m_hosts; }

  public void setClientId(String value) { m_client_id = value; }
  public String getClientId() { return m_client_id; }

  public void setCreatedBy(String value) { m_created_by = value; }
  public String getCreatedBy() { return m_created_by; }

  public void setCreatedDate(String value) { m_created_date = value; }
  public String getCreatedDate() { return m_created_date; }

  public void setUpdatedBy(String value) { m_updated_by = value; }
  public String getUpdatedBy() { return m_updated_by; }

  public void setUpdatedDate(String value) { m_updated_date = value; }
  public String getUpdatedDate() { return m_updated_date; }

  public void setExpirationDate(String value) { m_expiration_date = value; }
  public String getExpirationDate() { return m_expiration_date; }

  public void setTransferDate(String value) { m_transfer_date = value; }
  public String getTransferDate() { return m_transfer_date; }

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public String toString() { return this.getClass().getName() + ": { m_rsp ["+m_rsp+"] m_name ["+m_name+"] m_roid ["+m_roid+"] m_status ["+(m_status != null ? java.util.Arrays.asList(m_status) : null)+"] m_registrant ["+m_registrant+"] m_contacts ["+(m_contacts != null ? java.util.Arrays.asList(m_contacts) : null)+"] m_name_servers ["+(m_name_servers != null ? java.util.Arrays.asList(m_name_servers) : null)+"] m_hosts ["+(m_hosts != null ? java.util.Arrays.asList(m_hosts) : null)+"] m_client_id ["+m_client_id+"] m_created_by ["+m_created_by+"] m_created_date ["+m_created_date+"] m_updated_by ["+m_updated_by+"] m_updated_date ["+m_updated_date+"] m_expiration_date ["+m_expiration_date+"] m_transfer_date ["+m_transfer_date+"] m_auth_info ["+m_auth_info+"] }"; }

} // class epp_DomainInfoRsp
