package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainTransferReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/


///////////////////////
public class epp_DomainTransferReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public org.openrtk.idl.epp02.epp_TransferRequest m_trans = null;
  public String m_name = null;
  public org.openrtk.idl.epp02.domain.epp_DomainPeriod m_period = null;

  public epp_DomainTransferReq ()
  {
  } // ctor

  public epp_DomainTransferReq (org.openrtk.idl.epp02.epp_Command _m_cmd, org.openrtk.idl.epp02.epp_TransferRequest _m_trans, String _m_name, org.openrtk.idl.epp02.domain.epp_DomainPeriod _m_period)
  {
    m_cmd = _m_cmd;
    m_trans = _m_trans;
    m_name = _m_name;
    m_period = _m_period;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setTrans(org.openrtk.idl.epp02.epp_TransferRequest value) { m_trans = value; }
  public org.openrtk.idl.epp02.epp_TransferRequest getTrans() { return m_trans; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setPeriod(org.openrtk.idl.epp02.domain.epp_DomainPeriod value) { m_period = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainPeriod getPeriod() { return m_period; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_trans ["+m_trans+"] m_name ["+m_name+"] m_period ["+m_period+"] }"; }

} // class epp_DomainTransferReq
