package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainRenewReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/


////////////////////
public class epp_DomainRenewReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public String m_name = null;
  public String m_current_expiration_date = null;
  public org.openrtk.idl.epp02.domain.epp_DomainPeriod m_period = null;

  public epp_DomainRenewReq ()
  {
  } // ctor

  public epp_DomainRenewReq (org.openrtk.idl.epp02.epp_Command _m_cmd, String _m_name, String _m_current_expiration_date, org.openrtk.idl.epp02.domain.epp_DomainPeriod _m_period)
  {
    m_cmd = _m_cmd;
    m_name = _m_name;
    m_current_expiration_date = _m_current_expiration_date;
    m_period = _m_period;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setCurrentExpirationDate(String value) { m_current_expiration_date = value; }
  public String getCurrentExpirationDate() { return m_current_expiration_date; }

  public void setPeriod(org.openrtk.idl.epp02.domain.epp_DomainPeriod value) { m_period = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainPeriod getPeriod() { return m_period; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_name ["+m_name+"] m_current_expiration_date ["+m_current_expiration_date+"] m_period ["+m_period+"] }"; }

} // class epp_DomainRenewReq
