.SUFFIXES: .tgz

all:
	@echo building java rtk distribution \(no javadocs\)
	@./build.sh dist.nojavadoc

dist:
	@echo building java rtk distribution
	@./build.sh dist

jar:
	@echo building java rtk jar file
	@./build.sh jar

clean:
	@./build.sh clean

