package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactTransfer.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:13 PM EDT
*/

public interface epp_ContactTransfer extends epp_ContactTransferOperations, org.openrtk.idl.epp02.epp_Action, org.omg.CORBA.portable.IDLEntity 
{
} // interface epp_ContactTransfer
