package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactNameAddress.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:12 PM EDT
*/

public class epp_ContactNameAddress implements org.omg.CORBA.portable.IDLEntity
{
  public String m_name = null;
  public String m_org = null;
  public org.openrtk.idl.epp02.contact.epp_ContactAddress m_address = null;

  public epp_ContactNameAddress ()
  {
  } // ctor

  public epp_ContactNameAddress (String _m_name, String _m_org, org.openrtk.idl.epp02.contact.epp_ContactAddress _m_address)
  {
    m_name = _m_name;
    m_org = _m_org;
    m_address = _m_address;
  } // ctor

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setOrg(String value) { m_org = value; }
  public String getOrg() { return m_org; }

  public void setAddress(org.openrtk.idl.epp02.contact.epp_ContactAddress value) { m_address = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactAddress getAddress() { return m_address; }

  public String toString() { return this.getClass().getName() + ": { m_name ["+m_name+"] m_org ["+m_org+"] m_address ["+m_address+"] }"; }

} // class epp_ContactNameAddress
