package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactTransferReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:13 PM EDT
*/


////////////////////////
public class epp_ContactTransferReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public org.openrtk.idl.epp02.epp_TransferRequest m_trans = null;
  public String m_roid = null;

  public epp_ContactTransferReq ()
  {
  } // ctor

  public epp_ContactTransferReq (org.openrtk.idl.epp02.epp_Command _m_cmd, org.openrtk.idl.epp02.epp_TransferRequest _m_trans, String _m_roid)
  {
    m_cmd = _m_cmd;
    m_trans = _m_trans;
    m_roid = _m_roid;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setTrans(org.openrtk.idl.epp02.epp_TransferRequest value) { m_trans = value; }
  public org.openrtk.idl.epp02.epp_TransferRequest getTrans() { return m_trans; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_trans ["+m_trans+"] m_roid ["+m_roid+"] }"; }

} // class epp_ContactTransferReq
