package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactCreateReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:12 PM EDT
*/


//////////////////////
public class epp_ContactCreateReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress m_ascii_address = null;
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress m_i15d_address = null;
  public org.openrtk.idl.epp02.contact.epp_ContactPhone m_voice = null;
  public org.openrtk.idl.epp02.contact.epp_ContactPhone m_fax = null;
  public String m_email = null;
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;

  public epp_ContactCreateReq ()
  {
  } // ctor

  public epp_ContactCreateReq (org.openrtk.idl.epp02.epp_Command _m_cmd, org.openrtk.idl.epp02.contact.epp_ContactNameAddress _m_ascii_address, org.openrtk.idl.epp02.contact.epp_ContactNameAddress _m_i15d_address, org.openrtk.idl.epp02.contact.epp_ContactPhone _m_voice, org.openrtk.idl.epp02.contact.epp_ContactPhone _m_fax, String _m_email, org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info)
  {
    m_cmd = _m_cmd;
    m_ascii_address = _m_ascii_address;
    m_i15d_address = _m_i15d_address;
    m_voice = _m_voice;
    m_fax = _m_fax;
    m_email = _m_email;
    m_auth_info = _m_auth_info;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setAsciiAddress(org.openrtk.idl.epp02.contact.epp_ContactNameAddress value) { m_ascii_address = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress getAsciiAddress() { return m_ascii_address; }

  public void setI15dAddress(org.openrtk.idl.epp02.contact.epp_ContactNameAddress value) { m_i15d_address = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress getI15dAddress() { return m_i15d_address; }

  public void setVoice(org.openrtk.idl.epp02.contact.epp_ContactPhone value) { m_voice = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactPhone getVoice() { return m_voice; }

  public void setFax(org.openrtk.idl.epp02.contact.epp_ContactPhone value) { m_fax = value; }
  // included String version for backward compatibility
  public void setFax(String value) { m_fax = new org.openrtk.idl.epp02.contact.epp_ContactPhone("",value); }
  public org.openrtk.idl.epp02.contact.epp_ContactPhone getFax() { return m_fax; }

  public void setEmail(String value) { m_email = value; }
  public String getEmail() { return m_email; }

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_ascii_address ["+m_ascii_address+"] m_i15d_address ["+m_i15d_address+"] m_voice ["+m_voice+"] m_fax ["+m_fax+"] m_email ["+m_email+"] m_auth_info ["+m_auth_info+"] }"; }

} // class epp_ContactCreateReq
