package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainStatusType.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:06 PM EDT
*/


///////////////////////////
public class epp_DomainStatusType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 12;
  private static org.openrtk.idl.epp02.domain.epp_DomainStatusType[] __array = new org.openrtk.idl.epp02.domain.epp_DomainStatusType [__size];

  public static final int _HOLD = 0;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType HOLD = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_HOLD);
  public static final int _INACTIVE = 1;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType INACTIVE = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_INACTIVE);
  public static final int _LOCK = 2;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType LOCK = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_LOCK);
  public static final int _NEW = 3;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType NEW = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_NEW);
  public static final int _OK = 4;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType OK = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_OK);
  public static final int _PENDING_DELETE = 5;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType PENDING_DELETE = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_PENDING_DELETE);
  public static final int _PENDING_TRANSFER = 6;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType PENDING_TRANSFER = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_PENDING_TRANSFER);
  public static final int _PENDING_VERIFICATION = 7;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType PENDING_VERIFICATION = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_PENDING_VERIFICATION);
  public static final int _CLIENT_HOLD = 8;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType CLIENT_HOLD = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_CLIENT_HOLD);
  public static final int _CLIENT_LOCK = 9;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType CLIENT_LOCK = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_CLIENT_LOCK);
  public static final int _CLIENT_TRANSFER_PROHIBITED = 10;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType CLIENT_TRANSFER_PROHIBITED = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_CLIENT_TRANSFER_PROHIBITED);
  public static final int _ACTIVE = 11;
  public static final org.openrtk.idl.epp02.domain.epp_DomainStatusType ACTIVE = new org.openrtk.idl.epp02.domain.epp_DomainStatusType(_ACTIVE);

  public int value ()
  {
    return __value;
  }

  public static org.openrtk.idl.epp02.domain.epp_DomainStatusType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected epp_DomainStatusType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class epp_DomainStatusType
