package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainTransferOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/

public interface epp_DomainTransferOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.domain.epp_DomainTransferReq parms);
  org.openrtk.idl.epp02.domain.epp_DomainTransferRsp getResponseData ();
} // interface epp_DomainTransferOperations
