package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainCreateReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/


/////////////////////
public class epp_DomainCreateReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public String m_name = null;
  public org.openrtk.idl.epp02.domain.epp_DomainPeriod m_period = null;
  public String m_name_servers[] = null;
  public String m_registrant = null;
  public org.openrtk.idl.epp02.domain.epp_DomainContact m_contacts[] = null;
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;

  public epp_DomainCreateReq ()
  {
  } // ctor

  public epp_DomainCreateReq (org.openrtk.idl.epp02.epp_Command _m_cmd, String _m_name, org.openrtk.idl.epp02.domain.epp_DomainPeriod _m_period, String[] _m_name_servers, String _m_registrant, org.openrtk.idl.epp02.domain.epp_DomainContact[] _m_contacts, org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info)
  {
    m_cmd = _m_cmd;
    m_name = _m_name;
    m_period = _m_period;
    m_name_servers = _m_name_servers;
    m_registrant = _m_registrant;
    m_contacts = _m_contacts;
    m_auth_info = _m_auth_info;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setPeriod(org.openrtk.idl.epp02.domain.epp_DomainPeriod value) { m_period = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainPeriod getPeriod() { return m_period; }

  public void setNameServers(String[] value) { m_name_servers = value; }
  public String[] getNameServers() { return m_name_servers; }

  public void setRegistrant(String value) { m_registrant = value; }
  public String getRegistrant() { return m_registrant; }

  public void setContacts(org.openrtk.idl.epp02.domain.epp_DomainContact[] value) { m_contacts = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainContact[] getContacts() { return m_contacts; }

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_name ["+m_name+"] m_period ["+m_period+"] m_name_servers ["+(m_name_servers != null ? java.util.Arrays.asList(m_name_servers) : null)+"] m_registrant ["+m_registrant+"] m_contacts ["+(m_contacts != null ? java.util.Arrays.asList(m_contacts) : null)+"] m_auth_info ["+m_auth_info+"] }"; }

} // class epp_DomainCreateReq
