package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainContactType.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/

public class epp_DomainContactType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static org.openrtk.idl.epp02.domain.epp_DomainContactType[] __array = new org.openrtk.idl.epp02.domain.epp_DomainContactType [__size];

  public static final int _ADMIN = 0;
  public static final org.openrtk.idl.epp02.domain.epp_DomainContactType ADMIN = new org.openrtk.idl.epp02.domain.epp_DomainContactType(_ADMIN);
  public static final int _BILLING = 1;
  public static final org.openrtk.idl.epp02.domain.epp_DomainContactType BILLING = new org.openrtk.idl.epp02.domain.epp_DomainContactType(_BILLING);
  public static final int _TECH = 2;
  public static final org.openrtk.idl.epp02.domain.epp_DomainContactType TECH = new org.openrtk.idl.epp02.domain.epp_DomainContactType(_TECH);

  public int value ()
  {
    return __value;
  }

  public static org.openrtk.idl.epp02.domain.epp_DomainContactType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected epp_DomainContactType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class epp_DomainContactType
