package org.openrtk.idl.epp02.domain;


/**
* org/openrtk/idl/epp/domain/epp_DomainPeriod.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_domain.idl
* Thursday, July 26, 2001 6:26:07 PM EDT
*/


/////////////////////////////////////
public class epp_DomainPeriod implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.domain.epp_DomainPeriodUnitType m_unit = null;
  public short m_value = (short)0;

  public epp_DomainPeriod ()
  {
  } // ctor

  public epp_DomainPeriod (org.openrtk.idl.epp02.domain.epp_DomainPeriodUnitType _m_unit, short _m_value)
  {
    m_unit = _m_unit;
    m_value = _m_value;
  } // ctor

  public void setUnit(org.openrtk.idl.epp02.domain.epp_DomainPeriodUnitType value) { m_unit = value; }
  public org.openrtk.idl.epp02.domain.epp_DomainPeriodUnitType getUnit() { return m_unit; }

  public void setValue(short value) { m_value = value; }
  // added "int" setter by request of aeden at signaturedomains dot com
  public void setValue(int value) { m_value = (short)value; }
  public short getValue() { return m_value; }

  public String toString() { return this.getClass().getName() + ": { m_unit ["+m_unit+"] m_value ["+m_value+"] }"; }

} // class epp_DomainPeriod
