package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostDeleteRsp.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:10 PM EDT
*/

public class epp_HostDeleteRsp implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Response m_rsp = null;

  public epp_HostDeleteRsp ()
  {
  } // ctor

  public epp_HostDeleteRsp (org.openrtk.idl.epp02.epp_Response _m_rsp)
  {
    m_rsp = _m_rsp;
  } // ctor

  public void setRsp(org.openrtk.idl.epp02.epp_Response value) { m_rsp = value; }
  public org.openrtk.idl.epp02.epp_Response getRsp() { return m_rsp; }

  public String toString() { return this.getClass().getName() + ": { m_rsp ["+m_rsp+"] }"; }

} // class epp_HostDeleteRsp
