package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostStatusType.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:09 PM EDT
*/


///////////////////////////
public class epp_HostStatusType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static org.openrtk.idl.epp02.host.epp_HostStatusType[] __array = new org.openrtk.idl.epp02.host.epp_HostStatusType [__size];

  public static final int _LOCK = 0;
  public static final org.openrtk.idl.epp02.host.epp_HostStatusType LOCK = new org.openrtk.idl.epp02.host.epp_HostStatusType(_LOCK);
  public static final int _OK = 1;
  public static final org.openrtk.idl.epp02.host.epp_HostStatusType OK = new org.openrtk.idl.epp02.host.epp_HostStatusType(_OK);
  public static final int _PENDING_DELETE = 2;
  public static final org.openrtk.idl.epp02.host.epp_HostStatusType PENDING_DELETE = new org.openrtk.idl.epp02.host.epp_HostStatusType(_PENDING_DELETE);
  public static final int _CLIENT_LOCK = 3;
  public static final org.openrtk.idl.epp02.host.epp_HostStatusType CLIENT_LOCK = new org.openrtk.idl.epp02.host.epp_HostStatusType(_CLIENT_LOCK);

  public int value ()
  {
    return __value;
  }

  public static org.openrtk.idl.epp02.host.epp_HostStatusType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected epp_HostStatusType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class epp_HostStatusType
