package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostUpdateReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:10 PM EDT
*/

public class epp_HostUpdateReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public String m_name = null;
  public org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove m_add = null;
  public org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove m_remove = null;
  public org.openrtk.idl.epp02.host.epp_HostUpdateChange m_change = null;

  public epp_HostUpdateReq ()
  {
  } // ctor

  public epp_HostUpdateReq (org.openrtk.idl.epp02.epp_Command _m_cmd, String _m_name, org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove _m_add, org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove _m_remove, org.openrtk.idl.epp02.host.epp_HostUpdateChange _m_change)
  {
    m_cmd = _m_cmd;
    m_name = _m_name;
    m_add = _m_add;
    m_remove = _m_remove;
    m_change = _m_change;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setAdd(org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove value) { m_add = value; }
  public org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove getAdd() { return m_add; }

  public void setRemove(org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove value) { m_remove = value; }
  public org.openrtk.idl.epp02.host.epp_HostUpdateAddRemove getRemove() { return m_remove; }

  public void setChange(org.openrtk.idl.epp02.host.epp_HostUpdateChange value) { m_change = value; }
  public org.openrtk.idl.epp02.host.epp_HostUpdateChange getChange() { return m_change; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_name ["+m_name+"] m_add ["+m_add+"] m_remove ["+m_remove+"] m_change ["+m_change+"] }"; }

} // class epp_HostUpdateReq
