package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostUpdateChange.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:10 PM EDT
*/

public class epp_HostUpdateChange implements org.omg.CORBA.portable.IDLEntity
{
  public String m_name = null;

  public epp_HostUpdateChange ()
  {
  } // ctor

  public epp_HostUpdateChange (String _m_name)
  {
    m_name = _m_name;
  } // ctor

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public String toString() { return this.getClass().getName() + ": { m_name ["+m_name+"] }"; }

} // class epp_HostUpdateChange
