package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostCreateRsp.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:10 PM EDT
*/

public class epp_HostCreateRsp implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Response m_rsp = null;
  public String m_name = null;
  public String m_roid = null;

  public epp_HostCreateRsp ()
  {
  } // ctor

  public epp_HostCreateRsp (org.openrtk.idl.epp02.epp_Response _m_rsp, String _m_name, String _m_roid)
  {
    m_rsp = _m_rsp;
    m_name = _m_name;
    m_roid = _m_roid;
  } // ctor

  public void setRsp(org.openrtk.idl.epp02.epp_Response value) { m_rsp = value; }
  public org.openrtk.idl.epp02.epp_Response getRsp() { return m_rsp; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public String toString() { return this.getClass().getName() + ": { m_rsp ["+m_rsp+"] m_name ["+m_name+"] m_roid ["+m_roid+"] }"; }

} // class epp_HostCreateRsp
