package org.openrtk.idl.epp02.host;


/**
* org/openrtk/idl/epp/host/epp_HostInfoRsp.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_host.idl
* Thursday, July 26, 2001 6:26:09 PM EDT
*/

public class epp_HostInfoRsp implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Response m_rsp = null;
  public String m_name = null;
  public String m_roid = null;
  public boolean m_linked = false;
  public org.openrtk.idl.epp02.host.epp_HostStatus m_status[] = null;
  public org.openrtk.idl.epp02.host.epp_HostAddress m_addresses[] = null;
  public String m_client_id = null;
  public String m_created_by = null;
  public String m_created_date = null;
  public String m_updated_by = null;
  public String m_updated_date = null;
  public String m_transfer_date = null;

  public epp_HostInfoRsp ()
  {
  } // ctor

  public epp_HostInfoRsp (org.openrtk.idl.epp02.epp_Response _m_rsp, String _m_name, String _m_roid, boolean _m_linked, org.openrtk.idl.epp02.host.epp_HostStatus[] _m_status, org.openrtk.idl.epp02.host.epp_HostAddress[] _m_addresses, String _m_client_id, String _m_created_by, String _m_created_date, String _m_updated_by, String _m_updated_date, String _m_transfer_date)
  {
    m_rsp = _m_rsp;
    m_name = _m_name;
    m_roid = _m_roid;
    m_linked = _m_linked;
    m_status = _m_status;
    m_addresses = _m_addresses;
    m_client_id = _m_client_id;
    m_created_by = _m_created_by;
    m_created_date = _m_created_date;
    m_updated_by = _m_updated_by;
    m_updated_date = _m_updated_date;
    m_transfer_date = _m_transfer_date;
  } // ctor

  public void setRsp(org.openrtk.idl.epp02.epp_Response value) { m_rsp = value; }
  public org.openrtk.idl.epp02.epp_Response getRsp() { return m_rsp; }

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public void setLinked(boolean value) { m_linked = value; }
  public boolean getLinked() { return m_linked; }

  public void setStatus(org.openrtk.idl.epp02.host.epp_HostStatus[] value) { m_status = value; }
  public org.openrtk.idl.epp02.host.epp_HostStatus[] getStatus() { return m_status; }

  public void setAddresses(org.openrtk.idl.epp02.host.epp_HostAddress[] value) { m_addresses = value; }
  public org.openrtk.idl.epp02.host.epp_HostAddress[] getAddresses() { return m_addresses; }

  public void setClientId(String value) { m_client_id = value; }
  public String getClientId() { return m_client_id; }

  public void setCreatedBy(String value) { m_created_by = value; }
  public String getCreatedBy() { return m_created_by; }

  public void setCreatedDate(String value) { m_created_date = value; }
  public String getCreatedDate() { return m_created_date; }

  public void setUpdatedBy(String value) { m_updated_by = value; }
  public String getUpdatedBy() { return m_updated_by; }

  public void setUpdatedDate(String value) { m_updated_date = value; }
  public String getUpdatedDate() { return m_updated_date; }

  public void setTransferDate(String value) { m_transfer_date = value; }
  public String getTransferDate() { return m_transfer_date; }

  public String toString() { return this.getClass().getName() + ": { m_rsp ["+m_rsp+"] m_name ["+m_name+"] m_roid ["+m_roid+"] m_linked ["+m_linked+"] m_status ["+(m_status != null ? java.util.Arrays.asList(m_status) : null)+"] m_addresses ["+(m_addresses != null ? java.util.Arrays.asList(m_addresses) : null)+"] m_client_id ["+m_client_id+"] m_created_by ["+m_created_by+"] m_created_date ["+m_created_date+"] m_updated_by ["+m_updated_by+"] m_updated_date ["+m_updated_date+"] m_transfer_date ["+m_transfer_date+"] }"; }

} // class epp_HostInfoRsp
