package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactUpdateOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:13 PM EDT
*/

public interface epp_ContactUpdateOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.contact.epp_ContactUpdateReq parms);
  org.openrtk.idl.epp02.contact.epp_ContactUpdateRsp getResponseData ();
} // interface epp_ContactUpdateOperations
