package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactInfoOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:12 PM EDT
*/

public interface epp_ContactInfoOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.contact.epp_ContactInfoReq parms);
  org.openrtk.idl.epp02.contact.epp_ContactInfoRsp getResponseData ();
} // interface epp_ContactInfoOperations
