package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactInfoRsp.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:12 PM EDT
*/

public class epp_ContactInfoRsp implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Response m_rsp = null;
  public String m_roid = null;
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress m_ascii_address = null;
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress m_i15d_address = null;
  public org.openrtk.idl.epp02.contact.epp_ContactPhone m_voice = null;
  public org.openrtk.idl.epp02.contact.epp_ContactPhone m_fax = null;
  public String m_email = null;
  public org.openrtk.idl.epp02.contact.epp_ContactStatus m_status[] = null;
  public String m_client_id = null;
  public String m_created_by = null;
  public String m_created_date = null;
  public String m_expiration_date = null;
  public String m_updated_by = null;
  public String m_updated_date = null;
  public String m_transfer_date = null;
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;

  public epp_ContactInfoRsp ()
  {
  } // ctor

  public epp_ContactInfoRsp (org.openrtk.idl.epp02.epp_Response _m_rsp, String _m_roid, org.openrtk.idl.epp02.contact.epp_ContactNameAddress _m_ascii_address, org.openrtk.idl.epp02.contact.epp_ContactNameAddress _m_i15d_address, org.openrtk.idl.epp02.contact.epp_ContactPhone _m_voice, org.openrtk.idl.epp02.contact.epp_ContactPhone _m_fax, String _m_email, org.openrtk.idl.epp02.contact.epp_ContactStatus[] _m_status, String _m_client_id, String _m_created_by, String _m_created_date, String _m_expiration_date, String _m_updated_by, String _m_updated_date, String _m_transfer_date, org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info)
  {
    m_rsp = _m_rsp;
    m_roid = _m_roid;
    m_ascii_address = _m_ascii_address;
    m_i15d_address = _m_i15d_address;
    m_voice = _m_voice;
    m_fax = _m_fax;
    m_email = _m_email;
    m_status = _m_status;
    m_client_id = _m_client_id;
    m_created_by = _m_created_by;
    m_created_date = _m_created_date;
    m_expiration_date = _m_expiration_date;
    m_updated_by = _m_updated_by;
    m_updated_date = _m_updated_date;
    m_transfer_date = _m_transfer_date;
    m_auth_info = _m_auth_info;
  } // ctor

  public void setRsp(org.openrtk.idl.epp02.epp_Response value) { m_rsp = value; }
  public org.openrtk.idl.epp02.epp_Response getRsp() { return m_rsp; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public void setAsciiAddress(org.openrtk.idl.epp02.contact.epp_ContactNameAddress value) { m_ascii_address = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress getAsciiAddress() { return m_ascii_address; }

  public void setI15dAddress(org.openrtk.idl.epp02.contact.epp_ContactNameAddress value) { m_i15d_address = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactNameAddress getI15dAddress() { return m_i15d_address; }

  public void setVoice(org.openrtk.idl.epp02.contact.epp_ContactPhone value) { m_voice = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactPhone getVoice() { return m_voice; }

  public void setFax(org.openrtk.idl.epp02.contact.epp_ContactPhone value) { m_fax = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactPhone getFax() { return m_fax; }

  public void setEmail(String value) { m_email = value; }
  public String getEmail() { return m_email; }

  public void setStatus(org.openrtk.idl.epp02.contact.epp_ContactStatus[] value) { m_status = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactStatus[] getStatus() { return m_status; }

  public void setClientId(String value) { m_client_id = value; }
  public String getClientId() { return m_client_id; }

  public void setCreatedBy(String value) { m_created_by = value; }
  public String getCreatedBy() { return m_created_by; }

  public void setCreatedDate(String value) { m_created_date = value; }
  public String getCreatedDate() { return m_created_date; }

  public void setExpirationDate(String value) { m_expiration_date = value; }
  public String getExpirationDate() { return m_expiration_date; }

  public void setUpdatedBy(String value) { m_updated_by = value; }
  public String getUpdatedBy() { return m_updated_by; }

  public void setUpdatedDate(String value) { m_updated_date = value; }
  public String getUpdatedDate() { return m_updated_date; }

  public void setTransferDate(String value) { m_transfer_date = value; }
  public String getTransferDate() { return m_transfer_date; }

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public String toString() { return this.getClass().getName() + ": { m_rsp ["+m_rsp+"] m_roid ["+m_roid+"] m_ascii_address ["+m_ascii_address+"] m_i15d_address ["+m_i15d_address+"] m_voice ["+m_voice+"] m_fax ["+m_fax+"] m_email ["+m_email+"] m_status ["+(m_status != null ? java.util.Arrays.asList(m_status) : null)+"] m_client_id ["+m_client_id+"] m_created_by ["+m_created_by+"] m_created_date ["+m_created_date+"] m_expiration_date ["+m_expiration_date+"] m_updated_by ["+m_updated_by+"] m_updated_date ["+m_updated_date+"] m_transfer_date ["+m_transfer_date+"] m_auth_info ["+m_auth_info+"] }"; }

} // class epp_ContactInfoRsp
