package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactStatusType.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:12 PM EDT
*/


///////////////////////////
public class epp_ContactStatusType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static org.openrtk.idl.epp02.contact.epp_ContactStatusType[] __array = new org.openrtk.idl.epp02.contact.epp_ContactStatusType [__size];

  public static final int _LOCK = 0;
  public static final org.openrtk.idl.epp02.contact.epp_ContactStatusType LOCK = new org.openrtk.idl.epp02.contact.epp_ContactStatusType(_LOCK);
  public static final int _OK = 1;
  public static final org.openrtk.idl.epp02.contact.epp_ContactStatusType OK = new org.openrtk.idl.epp02.contact.epp_ContactStatusType(_OK);
  public static final int _PENDING_DELETE = 2;
  public static final org.openrtk.idl.epp02.contact.epp_ContactStatusType PENDING_DELETE = new org.openrtk.idl.epp02.contact.epp_ContactStatusType(_PENDING_DELETE);
  public static final int _PENDING_TRANSFER = 3;
  public static final org.openrtk.idl.epp02.contact.epp_ContactStatusType PENDING_TRANSFER = new org.openrtk.idl.epp02.contact.epp_ContactStatusType(_PENDING_TRANSFER);
  public static final int _CLIENT_LOCK = 4;
  public static final org.openrtk.idl.epp02.contact.epp_ContactStatusType CLIENT_LOCK = new org.openrtk.idl.epp02.contact.epp_ContactStatusType(_CLIENT_LOCK);
  public static final int _CLIENT_TRANSFER_PROHIBITED = 5;
  public static final org.openrtk.idl.epp02.contact.epp_ContactStatusType CLIENT_TRANSFER_PROHIBITED = new org.openrtk.idl.epp02.contact.epp_ContactStatusType(_CLIENT_TRANSFER_PROHIBITED);

  public int value ()
  {
    return __value;
  }

  public static org.openrtk.idl.epp02.contact.epp_ContactStatusType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected epp_ContactStatusType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class epp_ContactStatusType
