package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactDeleteOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:13 PM EDT
*/

public interface epp_ContactDeleteOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.contact.epp_ContactDeleteReq parms);
  org.openrtk.idl.epp02.contact.epp_ContactDeleteRsp getResponseData ();
} // interface epp_ContactDeleteOperations
