package org.openrtk.idl.epp02.contact;


/**
* org/openrtk/idl/epp/contact/epp_ContactUpdateReq.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp_contact.idl
* Thursday, July 26, 2001 6:26:13 PM EDT
*/

public class epp_ContactUpdateReq implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Command m_cmd = null;
  public String m_roid = null;
  public org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove m_add = null;
  public org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove m_remove = null;
  public org.openrtk.idl.epp02.contact.epp_ContactUpdateChange m_change = null;

  public epp_ContactUpdateReq ()
  {
  } // ctor

  public epp_ContactUpdateReq (org.openrtk.idl.epp02.epp_Command _m_cmd, String _m_roid, org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove _m_add, org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove _m_remove, org.openrtk.idl.epp02.contact.epp_ContactUpdateChange _m_change)
  {
    m_cmd = _m_cmd;
    m_roid = _m_roid;
    m_add = _m_add;
    m_remove = _m_remove;
    m_change = _m_change;
  } // ctor

  public void setCmd(org.openrtk.idl.epp02.epp_Command value) { m_cmd = value; }
  public org.openrtk.idl.epp02.epp_Command getCmd() { return m_cmd; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public void setAdd(org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove value) { m_add = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove getAdd() { return m_add; }

  public void setRemove(org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove value) { m_remove = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactUpdateAddRemove getRemove() { return m_remove; }

  public void setChange(org.openrtk.idl.epp02.contact.epp_ContactUpdateChange value) { m_change = value; }
  public org.openrtk.idl.epp02.contact.epp_ContactUpdateChange getChange() { return m_change; }

  public String toString() { return this.getClass().getName() + ": { m_cmd ["+m_cmd+"] m_roid ["+m_roid+"] m_add ["+m_add+"] m_remove ["+m_remove+"] m_change ["+m_change+"] }"; }

} // class epp_ContactUpdateReq
