package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_TransID.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:03 PM EDT
*/


//
public class epp_TransID implements org.omg.CORBA.portable.IDLEntity
{
  public String m_client_trid = null;
  public String m_server_trid = null;

  public epp_TransID ()
  {
  } // ctor

  public epp_TransID (String _m_client_trid, String _m_server_trid)
  {
    m_client_trid = _m_client_trid;
    m_server_trid = _m_server_trid;
  } // ctor

  public void setClientTrid(String value) { m_client_trid = value; }
  public String getClientTrid() { return m_client_trid; }

  public void setServerTrid(String value) { m_server_trid = value; }
  public String getServerTrid() { return m_server_trid; }

  public String toString() { return this.getClass().getName() + ": { m_client_trid ["+m_client_trid+"] m_server_trid ["+m_server_trid+"] }"; }

} // class epp_TransID
