package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_XMLException.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_XMLException extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public String m_error_message = null;

  public epp_XMLException ()
  {
  } // ctor

  public epp_XMLException (String _m_error_message)
  {
    m_error_message = _m_error_message;
  } // ctor

  public void setErrorMessage(String value) { m_error_message = value; }
  public String getErrorMessage() { return m_error_message; }

  public String toString() { return this.getClass().getName() + ": { m_error_message ["+m_error_message+"] }"; }

} // class epp_XMLException
