package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_HelloOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public interface epp_HelloOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  org.openrtk.idl.epp02.epp_Greeting getResponseData ();
} // interface epp_HelloOperations
