package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_TransferRequest.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_TransferRequest implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;
  public org.openrtk.idl.epp02.epp_TransferOpType m_op = null;

  public epp_TransferRequest ()
  {
  } // ctor

  public epp_TransferRequest (org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info, org.openrtk.idl.epp02.epp_TransferOpType _m_op)
  {
    m_auth_info = _m_auth_info;
    m_op = _m_op;
  } // ctor

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public void setOp(org.openrtk.idl.epp02.epp_TransferOpType value) { m_op = value; }
  public org.openrtk.idl.epp02.epp_TransferOpType getOp() { return m_op; }

  public String toString() { return this.getClass().getName() + ": { m_auth_info ["+m_auth_info+"] m_op ["+m_op+"] }"; }

} // class epp_TransferRequest
