package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_PollDomainTransfer.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_PollDomainTransfer implements org.omg.CORBA.portable.IDLEntity
{
  public String m_domain_name = null;
  public org.openrtk.idl.epp02.epp_AuthInfo m_auth_info = null;

  public epp_PollDomainTransfer ()
  {
  } // ctor

  public epp_PollDomainTransfer (String _m_domain_name, org.openrtk.idl.epp02.epp_AuthInfo _m_auth_info)
  {
    m_domain_name = _m_domain_name;
    m_auth_info = _m_auth_info;
  } // ctor

  public void setDomainName(String value) { m_domain_name = value; }
  public String getDomainName() { return m_domain_name; }

  public void setAuthInfo(org.openrtk.idl.epp02.epp_AuthInfo value) { m_auth_info = value; }
  public org.openrtk.idl.epp02.epp_AuthInfo getAuthInfo() { return m_auth_info; }

  public String toString() { return this.getClass().getName() + ": { m_domain_name ["+m_domain_name+"] m_auth_info ["+m_auth_info+"] }"; }

} // class epp_PollDomainTransfer
