package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Service.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_Service implements org.omg.CORBA.portable.IDLEntity
{
  public String m_name = null;
  public String m_xmlns = null;
  public String m_schema_location = null;

  public epp_Service ()
  {
  } // ctor

  public epp_Service (String _m_name, String _m_xmlns, String _m_schema_location)
  {
    m_name = _m_name;
    m_xmlns = _m_xmlns;
    m_schema_location = _m_schema_location;
  } // ctor

  public void setName(String value) { m_name = value; }
  public String getName() { return m_name; }

  public void setXmlns(String value) { m_xmlns = value; }
  public String getXmlns() { return m_xmlns; }

  public void setSchemaLocation(String value) { m_schema_location = value; }
  public String getSchemaLocation() { return m_schema_location; }

  public String toString() { return this.getClass().getName() + ": { m_name ["+m_name+"] m_xmlns ["+m_xmlns+"] m_schema_location ["+m_schema_location+"] }"; }

} // class epp_Service
