package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_CheckResult.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_CheckResult implements org.omg.CORBA.portable.IDLEntity
{
  public boolean m_exists = false;
  public String m_value = null;

  public epp_CheckResult ()
  {
  } // ctor

  public epp_CheckResult (boolean _m_exists, String _m_value)
  {
    m_exists = _m_exists;
    m_value = _m_value;
  } // ctor

  public void setExists(boolean value) { m_exists = value; }
  public boolean getExists() { return m_exists; }

  public void setValue(String value) { m_value = value; }
  public String getValue() { return m_value; }

  public String toString() { return this.getClass().getName() + ": { m_exists ["+m_exists+"] m_value ["+m_value+"] }"; }

} // class epp_CheckResult
