package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_AuthInfo.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:03 PM EDT
*/

public class epp_AuthInfo implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_AuthInfoType m_type = null;
  public String m_roid = null;
  public String m_value = null;

  public epp_AuthInfo ()
  {
  } // ctor

  public epp_AuthInfo (org.openrtk.idl.epp02.epp_AuthInfoType _m_type, String _m_roid, String _m_value)
  {
    m_type = _m_type;
    m_roid = _m_roid;
    m_value = _m_value;
  } // ctor

  public void setType(org.openrtk.idl.epp02.epp_AuthInfoType value) { m_type = value; }
  public org.openrtk.idl.epp02.epp_AuthInfoType getType() { return m_type; }

  public void setRoid(String value) { m_roid = value; }
  public String getRoid() { return m_roid; }

  public void setValue(String value) { m_value = value; }
  public String getValue() { return m_value; }

  public String toString() { return this.getClass().getName() + ": { m_type ["+m_type+"] m_roid ["+m_roid+"] m_value ["+m_value+"] }"; }

} // class epp_AuthInfo
