package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_PollOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public interface epp_PollOperations  extends org.openrtk.idl.epp02.epp_ActionOperations
{
  void setRequestData (org.openrtk.idl.epp02.epp_PollReq parms);
  org.openrtk.idl.epp02.epp_PollRsp getResponseData ();
} // interface epp_PollOperations
