package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Response.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/

public class epp_Response implements org.omg.CORBA.portable.IDLEntity
{
  public org.openrtk.idl.epp02.epp_Result m_results[] = null;
  public int m_qcount = (int)0;

  // expecting back from the registry.
  public String m_unspec_string = null;
  public org.openrtk.idl.epp02.epp_TransID m_trans_id = null;

  public epp_Response ()
  {
  } // ctor

  public epp_Response (org.openrtk.idl.epp02.epp_Result[] _m_results, int _m_qcount, String _m_unspec_string, org.openrtk.idl.epp02.epp_TransID _m_trans_id)
  {
    m_results = _m_results;
    m_qcount = _m_qcount;
    m_unspec_string = _m_unspec_string;
    m_trans_id = _m_trans_id;
  } // ctor

  public void setResults(org.openrtk.idl.epp02.epp_Result[] value) { m_results = value; }
  public org.openrtk.idl.epp02.epp_Result[] getResults() { return m_results; }

  public void setQcount(int value) { m_qcount = value; }
  public int getQcount() { return m_qcount; }

  public void setUnspecString(String value) { m_unspec_string = value; }
  public String getUnspecString() { return m_unspec_string; }

  public void setTransId(org.openrtk.idl.epp02.epp_TransID value) { m_trans_id = value; }
  public org.openrtk.idl.epp02.epp_TransID getTransId() { return m_trans_id; }

  public String toString() { return this.getClass().getName() + ": { m_results ["+(m_results != null ? java.util.Arrays.asList(m_results) : null)+"] m_qcount ["+m_qcount+"] m_unspec_string ["+m_unspec_string+"] m_trans_id ["+m_trans_id+"] }"; }

} // class epp_Response
