package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_UnspecOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/


// message.
public interface epp_UnspecOperations 
{
  String toXML () throws org.openrtk.idl.epp02.epp_XMLException;
  void fromXML (String xml) throws org.openrtk.idl.epp02.epp_XMLException;
} // interface epp_UnspecOperations
