package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_Greeting.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:04 PM EDT
*/


/////////////
public class epp_Greeting implements org.omg.CORBA.portable.IDLEntity
{
  public String m_server_id = null;
  public String m_server_date = null;
  public String m_versions[] = null;
  public String m_langs[] = null;
  public org.openrtk.idl.epp02.epp_Service m_services[] = null;

  public epp_Greeting ()
  {
  } // ctor

  public epp_Greeting (String _m_server_id, String _m_server_date, String[] _m_versions, String[] _m_langs, org.openrtk.idl.epp02.epp_Service[] _m_services)
  {
    m_server_id = _m_server_id;
    m_server_date = _m_server_date;
    m_versions = _m_versions;
    m_langs = _m_langs;
    m_services = _m_services;
  } // ctor

  public void setServerId(String value) { m_server_id = value; }
  public String getServerId() { return m_server_id; }

  public void setServerDate(String value) { m_server_date = value; }
  public String getServerDate() { return m_server_date; }

  public void setVersions(String[] value) { m_versions = value; }
  public String[] getVersions() { return m_versions; }

  public void setLangs(String[] value) { m_langs = value; }
  public String[] getLangs() { return m_langs; }

  public void setServices(org.openrtk.idl.epp02.epp_Service[] value) { m_services = value; }
  public org.openrtk.idl.epp02.epp_Service[] getServices() { return m_services; }

  public String toString() { return this.getClass().getName() + ": { m_server_id ["+m_server_id+"] m_server_date ["+m_server_date+"] m_versions ["+(m_versions != null ? java.util.Arrays.asList(m_versions) : null)+"] m_langs ["+(m_langs != null ? java.util.Arrays.asList(m_langs) : null)+"] m_services ["+(m_services != null ? java.util.Arrays.asList(m_services) : null)+"] }"; }

} // class epp_Greeting
