package org.openrtk.idl.epp02;


/**
* org/openrtk/idl/epp/epp_PollOpType.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from epp.idl
* Thursday, July 26, 2001 6:26:03 PM EDT
*/


//
public class epp_PollOpType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static org.openrtk.idl.epp02.epp_PollOpType[] __array = new org.openrtk.idl.epp02.epp_PollOpType [__size];

  public static final int _REQ = 0;
  public static final org.openrtk.idl.epp02.epp_PollOpType REQ = new org.openrtk.idl.epp02.epp_PollOpType(_REQ);
  public static final int _ACK = 1;
  public static final org.openrtk.idl.epp02.epp_PollOpType ACK = new org.openrtk.idl.epp02.epp_PollOpType(_ACK);

  public int value ()
  {
    return __value;
  }

  public static org.openrtk.idl.epp02.epp_PollOpType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected epp_PollOpType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class epp_PollOpType
